### ISSUE TITLE
chap05 eks.tf non supported attribute

### ISSUE THREAD

**Issue by andsus** [PacktPublishing/ArgoCD-in-Practice#4]
terraform plan -out=plan.out -var=zone_id=us-east-1
╷
│ Error: Unsupported argument
│ 
│   on eks.tf line 5, in module "eks":
│    5:   subnets         = module.vpc.private_subnets
│ 
│ An argument named "subnets" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on eks.tf line 14, in module "eks":
│   14:   workers_group_defaults = {
│ 
│ An argument named "workers_group_defaults" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on eks.tf line 18, in module "eks":
│   18:   worker_groups = [
│ 
│ An argument named "worker_groups" is not expected here.

**Comment by spirosoik** [comment]
Hello please use for EKS module 17.24.0 version please.

**Comment by JosephA-packt** [comment]
I hope your query has been answered @andsus.
